import { buildExamBank } from "./exam-content.js";
import { curriculumUnits } from "./curriculum.js";

export const topics = [
  { name: "Number", icon: "◉", color: "blue", subtopics: curriculumUnits.Number },
  { name: "Algebra", icon: "ƒ", color: "violet", subtopics: curriculumUnits.Algebra },
  { name: "Geometry", icon: "△", color: "orange", subtopics: curriculumUnits.Geometry },
  { name: "Mensuration", icon: "◱", color: "green", subtopics: curriculumUnits.Mensuration },
  { name: "Graphs", icon: "⌁", color: "pink", subtopics: curriculumUnits.Graphs },
  { name: "Trigonometry", icon: "∠", color: "teal", subtopics: curriculumUnits.Trigonometry },
  { name: "Statistics", icon: "▥", color: "yellow", subtopics: curriculumUnits.Statistics },
  { name: "Probability", icon: "◌", color: "red", subtopics: curriculumUnits.Probability },
];

export const questions = buildExamBank();

export const lessons = [
  { id: "number-percentages", topic: "Number", subtopic: "Percentages", title: "Percentages made simple", objective: "Calculate percentages of an amount and use percentages to solve problems.", explanation: "Percent means “out of 100”. Convert a percentage to a decimal by dividing by 100, then multiply by the amount. You can also find 10% by dividing by 10, and use that to build other percentages.", formula: "Percentage of an amount = (percentage ÷ 100) × amount", example: "Find 15% of 80.", steps: ["Find 10% of 80: 80 ÷ 10 = 8.", "Find 5% of 80: half of 8 = 4.", "Add them: 8 + 4 = 12."], practice: ["Find 20% of 60.", "Find 25% of 48."], challenge: "An item costs $80 after a 20% discount. Find its original price.", exam: "A population of 2400 increases by 15%. Calculate the new population.", summary: "Convert the percentage to a decimal and multiply, or break it into useful percentages such as 10% and 5%." },
  { id: "algebra-quadratics", topic: "Algebra", subtopic: "Quadratic equations", title: "Solving quadratic equations", objective: "Understand how to solve quadratic equations using factorisation.", explanation: "A quadratic equation can often be solved by factorising its left-hand side. When a product equals zero, at least one of its factors must be zero.", formula: "If (x + a)(x + b) = 0, then x = −a or x = −b.", example: "Solve x² + 5x + 6 = 0.", steps: ["Find two numbers that multiply to 6 and add to 5: 2 and 3.", "Factorise: (x + 2)(x + 3) = 0.", "Set each bracket to zero: x + 2 = 0 or x + 3 = 0.", "Therefore, x = −2 or x = −3."], practice: ["Solve x² + 7x + 12 = 0.", "Solve x² + 6x + 8 = 0."], challenge: "Solve 2x² + 7x + 3 = 0.", exam: "A rectangle has sides (x + 2) cm and (x + 3) cm. Its area is 30 cm². Find its dimensions.", summary: "Write the quadratic as a product of two brackets, then set each bracket equal to zero." },
  { id: "geometry-angles", topic: "Geometry", subtopic: "Angles", title: "Angles on a straight line", objective: "Use angle facts to calculate missing angles.", explanation: "Angles around a point make a full turn of 360°. Angles on a straight line make a half turn of 180°. These facts can help you calculate unknown angles without measuring.", formula: "Angles on a straight line sum to 180°", example: "One angle on a straight line is 68°. Find the other angle.", steps: ["Angles on a straight line sum to 180°.", "Subtract the known angle: 180 − 68 = 112°."], practice: ["Find the supplement of 45°.", "Angles on a line are x° and 125°. Find x."], challenge: "Three angles on a straight line are x°, 2x° and 30°. Find x.", exam: "Two straight lines intersect. One angle is 73°. Find the other three angles.", summary: "Identify the angle fact, write the total, then subtract the known angles." },
  { id: "probability-basics", topic: "Probability", subtopic: "Basic probability", title: "Getting started with probability", objective: "Calculate the probability of a single event.", explanation: "Probability describes how likely an event is. For equally likely outcomes, count the outcomes you want and divide by the total number of possible outcomes.", formula: "Probability = number of favourable outcomes ÷ total outcomes", example: "A fair die is rolled. Find the probability of a 6.", steps: ["There is 1 favourable outcome: a 6.", "There are 6 equally likely outcomes altogether.", "Therefore P(6) = 1/6."], practice: ["Find the probability of an even number on a fair die.", "A bag has 2 green and 6 yellow counters. Find P(green)."], challenge: "Two fair coins are flipped. Find the probability of two heads.", exam: "A box has red, blue and green beads in the ratio 2 : 3 : 5. One is chosen at random. Find the probability it is not red.", summary: "For equally likely outcomes, divide the number of favourable outcomes by the total." },
  { id: "statistics-averages", topic: "Statistics", subtopic: "Mean", title: "Mean, median and range", objective: "Calculate and interpret the mean, median, mode and range.", explanation: "The mean is the total divided by the number of values. The median is the middle value when the data is in order. The mode appears most often. The range is the largest value minus the smallest.", formula: "Mean = sum of values ÷ number of values; Range = maximum − minimum", example: "Find the mean and range of 3, 5, 7 and 9.", steps: ["Add the values: 3 + 5 + 7 + 9 = 24.", "Divide by 4 values: mean = 6.", "Subtract the smallest from the largest: range = 9 − 3 = 6."], practice: ["Find the mean of 4, 6 and 8.", "Find the median of 1, 2, 6, 8, 10."], challenge: "The mean of five numbers is 8. Four numbers total 29. Find the fifth number.", exam: "The mean of 6 values is 12. Five values total 53. Find the sixth value.", summary: "Order data for the median; add and divide for the mean; subtract extremes for the range." },
  { id: "mensuration-area", topic: "Mensuration", subtopic: "Area", title: "Area of rectangles and triangles", objective: "Choose and apply the correct formula to find a simple area.", explanation: "Area measures the space inside a 2D shape. For a rectangle, multiply its length by its width. A triangle with the same base and height as a rectangle has half its area.", formula: "Rectangle: A = length × width · Triangle: A = ½ × base × perpendicular height", example: "Find the area of a triangle with base 10 cm and perpendicular height 6 cm.", steps: ["Write the formula: area = ½ × base × height.", "Substitute the values: area = ½ × 10 × 6.", "Calculate: area = 30 cm²."], practice: ["Find the area of a rectangle 7 cm by 4 cm.", "Find the area of a triangle with base 8 cm and height 5 cm."], challenge: "A triangle has area 42 cm² and base 12 cm. Find its perpendicular height.", exam: "A rectangular garden measures 12 m by 8 m. Calculate its area.", summary: "Use the appropriate formula and include square units in your answer." },
  { id: "graphs-gradient", topic: "Graphs", subtopic: "Gradient", title: "Finding the gradient", objective: "Calculate the gradient of a straight line using two points.", explanation: "The gradient tells you how steep a line is. Choose two points on the line, find the change in their y-coordinates, and divide by the change in their x-coordinates.", formula: "Gradient = (y₂ − y₁) ÷ (x₂ − x₁)", example: "Find the gradient of the line through (1, 2) and (3, 8).", steps: ["Identify the coordinates: (x₁, y₁) = (1, 2), (x₂, y₂) = (3, 8).", "Find the change in y: 8 − 2 = 6.", "Find the change in x: 3 − 1 = 2.", "Divide: gradient = 6 ÷ 2 = 3."], practice: ["Find the gradient between (0, 1) and (2, 5).", "Find the gradient between (2, 7) and (5, 1)."], challenge: "A line has gradient 4 and passes through (2, 3). Find the y-coordinate when x = 5.", exam: "Calculate the gradient of the straight line joining (−1, 4) and (3, 12).", summary: "Use change in y divided by change in x, keeping the coordinate order consistent." },
  { id: "trigonometry-pythagoras", topic: "Trigonometry", subtopic: "Pythagoras' theorem", title: "Pythagoras' theorem", objective: "Find a missing side in a right-angled triangle.", explanation: "Pythagoras' theorem links the lengths of the three sides of a right-angled triangle. The hypotenuse is the longest side, opposite the right angle.", formula: "a² + b² = c² (where c is the hypotenuse)", example: "A right triangle has shorter sides 6 cm and 8 cm. Find the hypotenuse.", steps: ["Identify the two shorter sides: a = 6, b = 8.", "Substitute: c² = 6² + 8² = 36 + 64 = 100.", "Take the positive square root: c = 10 cm."], practice: ["Find the hypotenuse when the shorter sides are 5 cm and 12 cm.", "A triangle has hypotenuse 13 cm and one shorter side 5 cm. Find the other side."], challenge: "A 10 m ladder reaches 8 m up a wall. How far is its base from the wall?", exam: "A right-angled triangle has shorter sides 9 cm and 12 cm. Calculate its hypotenuse.", summary: "Square the two shorter sides and add them to find the hypotenuse squared." },
];

export const achievements = [
  { id: "first-lesson", name: "First steps", description: "Complete your first lesson", icon: "✦", rule: u => u.profile.completedLessons.length >= 1 },
  { id: "first-ten", name: "Getting warmed up", description: "Answer 10 questions", icon: "✎", rule: u => u.profile.questionsCompleted >= 10 },
  { id: "century", name: "Century club", description: "Answer 100 questions", icon: "💯", rule: u => u.profile.questionsCompleted >= 100 },
  { id: "five-hundred", name: "Five hundred strong", description: "Answer 500 questions", icon: "500", rule: u => u.profile.questionsCompleted >= 500 },
  { id: "streak-7", name: "Week of wins", description: "Build a 7-day streak", icon: "🔥", rule: u => u.profile.streak >= 7 },
  { id: "streak-30", name: "Month of momentum", description: "Build a 30-day streak", icon: "🌿", rule: u => u.profile.streak >= 30 },
  { id: "exam-champ", name: "Exam champion", description: "Complete a mock exam", icon: "🏆", rule: u => u.profile.exams.some(exam => !exam.diagnostic) },
  { id: "algebra-master", name: "Algebra master", description: "Score 80% in Algebra", icon: "ƒ", rule: u => (u.profile.topicScores.Algebra ?? 0) >= 80 },
  { id: "geometry-master", name: "Geometry master", description: "Score 80% in Geometry", icon: "△", rule: u => (u.profile.topicScores.Geometry ?? 0) >= 80 },
  { id: "probability-pro", name: "Probability pro", description: "Score 80% in Probability", icon: "◌", rule: u => (u.profile.topicScores.Probability ?? 0) >= 80 },
  { id: "a-star-goal", name: "A* goal", description: "Set A* as your target and score 80% or more in a mock exam", icon: "★", rule: u => u.profile.target === "A*" && u.profile.exams.some(exam => !exam.diagnostic && exam.percentage >= 80) },
];
