import { cloudEnabled } from "./cloud.js";
import { buildWorkingRubric, reviewWorking, summariseWorkingReviews, markingGuideUrl, papaCambridgeUrl, markingPrinciples } from "./working-review.js";
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

export function renderUploadPanel(files = [], index = 0, context = "exam", busy = false) {
  return `<section class="working-uploads"><div class="working-upload-heading"><div><span class="eyebrow">WORK ON PAPER</span><h3>Attach your working</h3></div><span>${files.length}/5 files</span></div><p>Write the question number and part letters on your paper. Take a clear photo of every step or attach a PDF.</p><label class="working-file-picker">Choose photos or a PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple data-working-upload="${context}" data-working-question="${index}" ${busy ? "disabled" : ""}></label><small>JPG, PNG, WebP or PDF · Up to 10 MB per file · ${cloudEnabled ? "Saved privately to your account; available to the administrator." : "Saved in this browser; never sent to a server."}</small>${busy ? `<p role="status">Saving your upload…</p>` : ""}<div class="working-file-list">${files.map(file => `<article class="working-file"><div>${file.type.startsWith("image/") ? `<img data-work-preview="${esc(file.id)}" alt="Paper working: ${esc(file.name)}" loading="lazy">` : `<span class="working-pdf-icon">PDF</span>`}<p><strong>${esc(file.name)}</strong><small>${(file.size / 1024 / 1024).toFixed(1)} MB</small></p><a data-work-open="${esc(file.id)}" target="_blank" rel="noopener noreferrer">Open full size ↗</a></div><button type="button" class="text-button" data-remove-working="${esc(file.id)}" data-working-context="${context}" data-working-question="${index}" ${busy ? "disabled" : ""}>Remove attachment</button></article>`).join("")}</div></section>`;
}

export function renderMarkingGuide() {
  return `<details class="working-marking-guide"><summary>How the marking works · M, A and B marks</summary><dl>${markingPrinciples.map(principle => `<dt>${principle.code} marks</dt><dd>${esc(principle.description)}</dd>`).join("")}</dl><p>Credit equivalent valid methods. Use whole marks. Do not deduct marks already earned. Follow-through credit and special cases apply only when the matching question's scheme allows them.</p><p>These are original practice rubrics using Cambridge-style mark types. For an official past paper, use the mark scheme for its exact year, session and paper variant.</p><div class="official-paper-actions"><a href="${markingGuideUrl}" target="_blank" rel="noopener noreferrer">Cambridge marking guidance ↗</a><a href="${papaCambridgeUrl}" target="_blank" rel="noopener noreferrer">PapaCambridge papers & mark schemes ↗</a></div></details>`;
}

export function renderMethodCriteria(part, review = {}, questionIndex, partIndex) {
  const score = reviewWorking(part, review);
  return `<section class="method-review"><div class="method-review-heading"><h4>Review part ${String.fromCharCode(97 + partIndex)}</h4><span>${score.earned}/${score.total} ${score.complete ? "reviewed marks" : "marks so far"}</span></div><p>Inspect the uploaded working or written steps. Confirm each criterion; a valid equivalent method can earn credit. An accuracy mark needs its associated method, seen or implied.</p><div class="method-review-shortcuts"><button type="button" class="text-button" data-review-all="earned" data-method-question="${questionIndex}" data-method-part="${partIndex}">Award all criteria after review</button><button type="button" class="text-button" data-review-all="not-earned" data-method-question="${questionIndex}" data-method-part="${partIndex}">No criteria earned</button></div>${buildWorkingRubric(part).map(criterion => `<label class="method-criterion"><span class="mark-code">${criterion.code}${criterion.marks}</span><span>${esc(criterion.description)}${criterion.dependsOn.length ? `<small>Requires ${criterion.dependsOn.map(id => `${buildWorkingRubric(part).find(c => c.id === id).code}1`).join(" + ")}</small>` : ""}</span><select data-method-criterion="${criterion.id}" data-method-question="${questionIndex}" data-method-part="${partIndex}" aria-label="${criterion.code}${criterion.marks} criterion ${Number(criterion.id.slice(1)) + 1} for part ${String.fromCharCode(97 + partIndex)}">${[["pending", "Not reviewed"], ["earned", "Earned"], ["not-earned", "Not earned"]].map(([value, label]) => `<option value="${value}" ${value === (review.decisions?.[criterion.id] || "pending") ? "selected" : ""}>${label}</option>`).join("")}</select></label>`).join("")}<label class="review-note-label">Feedback from the reviewer<textarea rows="2" data-review-note="${questionIndex}" data-review-part="${partIndex}" placeholder="Explain the first error, credit an alternative method, or note how to improve.">${esc(review.note || "")}</textarea></label><div class="method-feedback" role="status"><strong>${score.complete ? "Feedback on your working" : "Review in progress"}</strong><ul>${score.feedback.map(message => `<li>${esc(message)}</li>`).join("")}</ul></div></section>`;
}

export function workingReviewSummary(result) {
  const summary = summariseWorkingReviews(result.review);
  return `<section class="working-review-summary"><div><span class="eyebrow">${summary.complete ? "REVIEWED PAPER" : "MARKING IN PROGRESS"}</span><h2>${summary.complete ? `${summary.earned} / ${summary.total} marks` : "Your working is ready to review."}</h2><p>${summary.reviewedParts}/${summary.totalParts} parts reviewed${summary.complete ? ` · ${summary.percentage}%` : ` · ${summary.earned} marks awarded so far`}</p></div><label>Reviewed by<select id="working-reviewer"><option value="self" ${result.reviewer !== "teacher" ? "selected" : ""}>Learner · self-review</option><option value="teacher" ${result.reviewer === "teacher" ? "selected" : ""}>Teacher / tutor · local review</option></select></label><p class="working-review-status">Photos and PDFs are reviewed by a person here. The app calculates marks and feedback from those decisions; it does not read handwriting automatically. ${summary.complete ? "This is a reviewed practice score." : result.mode === "upload" ? "No final score is recorded until every criterion is reviewed." : "Your final-answer check remains separate until the method review is complete."}</p></section>`;
}
